wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722766266
    t:
      1:
      - 1
      - 5
      - 40
      - 53
      - 55
      2:
      - 1
      - 5
      - 40
      - 53
      - 55
      3:
      - 3
      - 23
      4: 3.12.4
      5: 0.17.5
      8:
      - 5
      13: darwin-x86_64
